# Generated by Django 6.1 on 2026-09-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, default="", max_length=256)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("email_verification", "Email Verification"),
                            ("password_reset", "Password Reset"),
                        ],
                        default="login",
                        max_length=32,
                    ),
                ),
                ("code", models.CharField(max_length=128)),
                ("attempts_count", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "is_used", "expires_at"],
                        name="accounts_ot_email_0ff7ad_idx",
                    ),
                    models.Index(
                        fields=["user", "purpose", "is_used", "expires_at"],
                        name="accounts_ot_user_id_523eb6_idx",
                    ),
                    models.Index(
                        fields=["email", "created_at"],
                        name="accounts_ot_email_4c9cd8_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("user__isnull", False),
                            models.Q(("email", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="otp_has_recipient",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("attempts_count__lte", models.F("max_attempts"))
                        ),
                        name="otp_attempts_within_limit",
                    ),
                ],
            },
        ),
    ]
